spring.application.name=insurance-api

# ===================================
# DATABASE
# ===================================
# Local PostgreSQL (dev)
spring.datasource.url=jdbc:postgresql://localhost:5432/insurance
spring.datasource.username=postgres
spring.datasource.password=Toto1982!!!
spring.datasource.driver-class-name=org.postgresql.Driver